In [162]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [163]:
df=pd.read_csv("spam.csv")f
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [164]:
df.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [165]:
# df["spam"]=df["Category"].apply(lambda x:1 if x=="spam" else 0)

In [166]:
df["Category"]=df["Category"].map({"ham":0,"spam":1})

In [167]:
df

Category                                            Message
0            0  Go until jurong point, crazy.. Available only ...
1            0                      Ok lar... Joking wif u oni...
2            1  Free entry in 2 a wkly comp to win FA Cup fina...
3            0  U dun say so early hor... U c already then say...
4            0  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5567         1  This is the 2nd time we have tried 2 contact u...
5568         0               Will ü b going to esplanade fr home?
5569         0  Pity, * was in mood for that. So...any other s...
5570         0  The guy did some bitching but I acted like i'd...
5571         0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [168]:
X=df.Message
y=df.Category

In [169]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

In [98]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train= v.fit_transform(X_train)
X_test= v.transform(X_test)
X_train.toarray()[:3]
X_test.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3, 7701))

In [99]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
model = MultinomialNB()
parameter = {'alpha': [0.1, 0.5, 1.0, 2.0],'fit_prior': [True, False]
}

In [100]:
nb_model = GridSearchCV(model, param_grid=parameter,scoring="accuracy",cv=5)
nb_model.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=MultinomialNB(),
             param_grid={'alpha': [0.1, 0.5, 1.0, 2.0],
                         'fit_prior': [True, False]},
             scoring='accuracy')

In [101]:
print(nb_model.best_params_)

{'alpha': 0.1, 'fit_prior': True}


In [102]:
print(nb_model.best_score_)

0.9795823204642338


In [103]:
y_pred=nb_model.predict(X_test)

In [110]:
from sklearn.metrics import accuracy_score,classification_report

In [111]:
score=accuracy_score(y_pred,y_test)

In [113]:
print(score)

0.989237668161435


In [115]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       970
           1       0.95      0.97      0.96       145

    accuracy                           0.99      1115
   macro avg       0.97      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [116]:
emails = ["Hey Mohan, Can we go together to watch football match tomorrow ? ",
          "Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward" 
         ]

In [117]:
email_count=v.transform(emails)
nb_model.predict(email_count)

array([0, 1])

In [119]:
nb_model.score(X_test,y_test)

0.989237668161435

In [121]:
nb_model.score(X_test,y_test)

0.989237668161435

In [ ]:
## Solving the same question by pipeline and for that we are using raw text data only..... by pipeline it is converting into spearse matrix 
## and naive bayes theorem apllying in aa single step.... 

In [170]:
from sklearn.pipeline import Pipeline 
pl=Pipeline([("vector",CountVectorizer()),
             ("nb", MultinomialNB())])

In [171]:
pl.fit(X_train,y_train)

Pipeline(steps=[('vector', CountVectorizer()), ('nb', MultinomialNB())])

In [172]:
pl.score(X_test,y_test)

0.9919282511210762

In [174]:
pl.predict(emails)

array([0, 1])