In [19]:
import numpy as np 

In [20]:
 my_lst=[1,2,3,4,5]

In [21]:
print(my_lst)

[1, 2, 3, 4, 5]


In [22]:
arr=np.array(my_lst)

In [23]:
arr[3]

np.int64(4)

In [24]:
print(arr)

[1 2 3 4 5]


In [25]:
type(arr)

numpy.ndarray

In [26]:
arr

array([1, 2, 3, 4, 5])

In [27]:
arr.shape

(5,)

In [33]:
 my_lst1=[1,2,3,4,5]
 my_lst2=[2,3,4,6,7]
 my_lst3=[5,6,8,9,0]

In [34]:
arr1=np.array([my_lst1,my_lst2,my_lst3])

In [35]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 6, 7],
       [5, 6, 8, 9, 0]])

In [31]:
arr1.shape

(3, 5)

In [32]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 6],
       [7, 5, 6],
       [8, 9, 0]])

In [40]:
arr1[1:2,1:4]

array([[3, 4, 6]])

In [42]:
arr1[-2,:-1]

array([2, 3, 4, 6])

In [49]:
arr2=np.arange(0,20,step=2)

In [50]:
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [51]:
arr2[3:]=100

In [52]:
arr2

array([  0,   2,   4, 100, 100, 100, 100, 100, 100, 100])

In [53]:
arr3=arr2.copy()

In [54]:
arr3

array([  0,   2,   4, 100, 100, 100, 100, 100, 100, 100])

In [55]:
print(arr2)
arr3[3:]=1000
print(arr3)

[  0   2   4 100 100 100 100 100 100 100]
[   0    2    4 1000 1000 1000 1000 1000 1000 1000]


In [57]:
val=2
arr3<2

array([ True, False, False, False, False, False, False, False, False,
       False])

In [58]:
arr3*2

array([   0,    4,    8, 2000, 2000, 2000, 2000, 2000, 2000, 2000])

In [59]:
arr3/2

array([  0.,   1.,   2., 500., 500., 500., 500., 500., 500., 500.])

In [62]:
arr3[arr3<200]

array([0, 2, 4])

In [64]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [76]:
arr_ex=np.random.rand(4,4) ##between 0-1

In [77]:
arr_ex

array([[0.54775015, 0.97217313, 0.87273962, 0.34114219],
       [0.99739888, 0.32171457, 0.33967786, 0.3190687 ],
       [0.80321775, 0.39817208, 0.32129592, 0.90386963],
       [0.96321599, 0.63966174, 0.02006015, 0.82363742]])

In [79]:
arr_ex1=np.random.randn(4,4) 

In [80]:
arr_ex1

array([[-0.05285316,  1.27600937, -0.13580772,  0.17969972],
       [ 0.85148061, -0.06785173,  0.9464409 ,  0.29949893],
       [-0.85151947,  0.52280161,  1.17438531,  0.41975346],
       [ 0.26562941,  0.28272221, -1.56003531,  0.08404757]])

In [81]:
np.random.randint(0,100,8)

array([93, 40, 27, 68, 30, 33, 66, 65], dtype=int32)

In [85]:
np.random.random_sample((1,5))

array([[0.55931   , 0.63708626, 0.42446322, 0.65640902, 0.42989512]])